### ISSUE TITLE
ClassCastException when publishing to subscribers compiled with java1.8

### ISSUE THREAD

**Issue by romikk** [bennidi/mbassador#101]
This code
```java
    public class Subscription<T> {
        protected void onMessage(T msg){}
    }

   public class TestClient {
      public static void main(String[] args) throws Exception {
      // initialise MBassador
      //...
        bus.subscribe(new Subscription<MyEvent>() {
            @Handler
            public void onMessage(final MyEvent msg) {
                System.out.println(msg);
            }
        });
        bus.publish(new MyOtherEvent());
     }
   }
```
Throws an exception
```java
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:41)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:66)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:46)
	at net.engio.mbassy.bus.MBassador.publish(MBassador.java:46)
	at com.sandbox.TestClient.main(TestClient.java:58)
Caused by: java.lang.ClassCastException: com.sandbox.message.MyOtherEvent cannot be cast to com.sandbox.message.MyEvent
	at com.sandbox.TestClient$1.onMessage(TestClient.java:51)
	... 17 more
```

Which is most likely to be caused by the fact that for classes compiled with java8 `Class.getDeclaredMethods()` will return results different to what used to be in java7 and prior.
More on this here:
http://stackoverflow.com/questions/27013542/getdeclaredmethods-behaving-differently-in-java-7-vs-java-8

**Comment by bennidi** [comment]
@romikk Maybe you could try to solve this issue? I am very swamped with work from other projects. Your help would be very appreciated.
