### ISSUE TITLE
NullPointers when declaring no features

### ISSUE THREAD

**Issue by Prototype1** [bennidi/mbassador#110]
Hi, 

when i do something like this: 

private final MBassador<Message> bus = new MBassador<>(
			new BusConfiguration()); 

I get this exception: 

Exception in thread "main" java.lang.NullPointerException
	at net.engio.mbassy.bus.AbstractPubSubSupport.<init>(AbstractPubSubSupport.java:47)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus.<init>(AbstractSyncAsyncMessageBus.java:36)
	at net.engio.mbassy.bus.MBassador.<init>(MBassador.java:17)

I assume this is because properties Map in BusConfiguration isnt filled with default values. 

At least it should have this feature  (Feature.SyncPubSub ) as default one. 

However when I add this manually it still wont start because it also lacks  
Feature.AsynchronousMessageDispatch.Default()
and 
Feature.AsynchronousMessageDispatch.Default()

So this line 
private final MBassador<Message> bus = new MBassador<>(
			new BusConfiguration()); 

for guys who just want to start quick and dirty :) doesnt work. 

I use the newest version from maven repo :
<version>1.2.1</version>

Thanks for looking it up

**Comment by Prototype1** [comment]
Hi,

i didnt saw that MBassdor also has a default constructor (no IDE right now). So this is pretty much void... 

Sorry...
